version: "3.9"

services:
  db:
    image: mysql:8.1.0
    container_name: db
#    expose:
#      - "3306"
#    ports:
#      - "3307:3306"
    environment:
      - MYSQL_DATABASE=bootcamp
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
    volumes:
      - ./db/init-data.sql:/docker-entrypoint-initdb.d/init.sql
      - db:/var/lib/mysql
  task-app:
    build:
      context: .\
      dockerfile: Dockerfile
    container_name: task-app
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
#      - spring.datasource.url=jdbc:mysql://db:3307/bootcamp
      - spring.datasource.url=jdbc:mysql://db/bootcamp
      - spring.datasource.username=user
      - spring.datasource.password=pass
      - spring.sql.init.mode=always
    depends_on:
      - db
volumes:
  db: {}

